---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 11.10.4

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[teamcity::server]
    attributes:
