---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 11.10.4
  customize:
    memory: 512

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
      - recipe[mysql::server]

suites:
  - name: default
    run_list:
      - recipe[teamcity::server]
      - recipe[teamcity::mysql]
      - recipe[teamcity::agent]
      - recipe[teamcity::nginx]
      - recipe[teamcity::build_tools]
    attributes:
      teamcity:
        agent:
          rubies: [2.1.1]
      mysql:
        server_root_password: rootpass
        server_debian_password: debpass
        server_repl_password: replpass
        bind_address: 0.0.0.0
